Upgrade google to v5.0 for scheduled_queries
terraform-google-modules/terraform-google-bigquery pull request #259
Opened 2023-10-04 12:50 UTC by LloydArmstrong

When trying to upgrade the `hashicorp/google` version to 5.0, the `scheduled_queries` submodule fails due to it's requirement of `~>4.0`. 

My familiarity with this specific submodule is not extensive and therefor, I'm not entirely sure of breaking changes. Please let me know if this is not support as of yet.

2023-10-04 13:56 UTC, LloydArmstrong commented
I realise this is a much bigger issue due to the dependancy on other Terraform Modules that have the same constraints, (even just within the testing module)

- kms
- project-factory

Even just to test this, it will require parallel MR's with the same versioning changes. It will require a concerted and synchronised effort between all modules involved

2023-10-04 15:17 UTC, apeabody commented on test/setup/versions.tf
> +      version = ">= 3.53.0, ~> 5.0"
```suggestion
      version = ">= 3.53.0, < 6"
```

2023-10-04 15:17 UTC, apeabody commented on test/setup/versions.tf
> +      version = ">= 3.53.0, ~> 5.0"
```suggestion
      version = ">= 3.53.0, < 6"
```

2023-10-04 15:17 UTC, apeabody commented on versions.tf
> +      version = ">= 4.42, ~> 5.0"
```suggestion
      version = ">= 4.42, < 6"
```

2023-10-04 15:20 UTC, apeabody requested changes
Thanks @LloydArmstrong! - We should avoid making this a breaking change by leaving the minimum version requirements intact and lifting the maximum.

2023-10-05 15:11 UTC, apeabody commented
/gcbrun

2023-10-09 09:12 UTC, LloydArmstrong commented
/gcbrun

2023-10-09 09:13 UTC, LloydArmstrong commented
I've fixed the commit message convention used. Please take another look. Thanks.

2023-10-09 15:50 UTC, apeabody commented
/gcbrun

2023-10-09 16:27 UTC, apeabody approved these changes

2023-10-09 16:28 UTC, merged